/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaacademico;

/**
 *
 * @author esteb
 */
public class VentanaMaterias extends javax.swing.JFrame {

    public VentanaMaterias() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
private void cargarTabla() {
    String[] columnas = {"Docente", "Materias Asignadas"};
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    String sql = "SELECT d.nombre AS docente, " +
                 "(SELECT GROUP_CONCAT(m.nombre SEPARATOR ', ') FROM docente_materias dm " +
                 "INNER JOIN materias m ON dm.materia_id = m.id " +
                 "WHERE dm.docente_id = d.id) AS materias " +
                 "FROM docentes d";

    try (java.sql.PreparedStatement ps = this.conexion.prepareStatement(sql);
         java.sql.ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            String docente = rs.getString("docente");
            String materias = rs.getString("materias");
            if (materias == null || materias.isEmpty()) {
                materias = "Ninguna";
            }
            Object[] fila = {docente, materias};
            modelo.addRow(fila);
        }

    } catch (java.sql.SQLException e) {
        System.out.println("Error al cargar tabla de materias: " + e.getMessage());
    }

    tablaAsignacion.setModel(modelo);
}







    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaMaterias.class.getName());

    /**
     * Creates new form VentanaMaterias
     */
     private java.sql.Connection conexion;

    public VentanaMaterias(java.sql.Connection conexion) {
        initComponents();
        this.conexion = conexion;
        cargarTabla();
        cargarComboDocentes();
        cargarComboMaterias();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonAsignar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAsignacion = new javax.swing.JTable();
        botonEliminarMateria = new javax.swing.JButton();
        comboDocentes = new javax.swing.JComboBox<>();
        comboMaterias = new javax.swing.JComboBox<>();
        botonregresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre Docente ");

        jLabel2.setText("Nombre Materia ");

        botonAsignar.setText("Asignar Materia");
        botonAsignar.addActionListener(this::botonAsignarActionPerformed);

        tablaAsignacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Docente", "Materias"
            }
        ));
        jScrollPane1.setViewportView(tablaAsignacion);

        botonEliminarMateria.setText("Eliminar Materia Seleccionada");
        botonEliminarMateria.addActionListener(this::botonEliminarMateriaActionPerformed);

        comboDocentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDocentes.addActionListener(this::comboDocentesActionPerformed);

        comboMaterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMaterias.addActionListener(this::comboMateriasActionPerformed);

        botonregresar.setText("Regresar");
        botonregresar.addActionListener(this::botonregresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(comboDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGap(61, 61, 61)
                        .addComponent(comboMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAsignar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonEliminarMateria)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonregresar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAsignar))
                .addGap(33, 33, 33)
                .addComponent(botonEliminarMateria)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonregresar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void botonEliminarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarMateriaActionPerformed
int fila = tablaAsignacion.getSelectedRow();
if (fila == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un docente de la tabla");
    return;
}

String docente = tablaAsignacion.getValueAt(fila, 0).toString();
String sql = "DELETE FROM docente_materias WHERE docente_id = (SELECT idUsuario FROM usuarios WHERE nombre = ? LIMIT 1)";

int confirmar = javax.swing.JOptionPane.showConfirmDialog(this, "¿Desasociar todas las materias de " + docente + "?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
    try (java.sql.PreparedStatement ps = this.conexion.prepareStatement(sql)) {
        ps.setString(1, docente);
        ps.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Asignaciones eliminadas");
        cargarTabla();
    } catch (java.sql.SQLException e) {
        System.out.println("Error: " + e.getMessage());
    }
}

        
// TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarMateriaActionPerformed

    private void botonAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarActionPerformed
if (comboDocentes.getSelectedItem() == null || comboMaterias.getSelectedItem() == null) {
    javax.swing.JOptionPane.showMessageDialog(this, "Por favor seleccione un docente y una materia");
    return;
}

try {
    String docenteSeleccionado = comboDocentes.getSelectedItem().toString();
    int idDocente = Integer.parseInt(docenteSeleccionado.split(" - ")[0]);

    String mS = comboMaterias.getSelectedItem().toString();
    int idMateria = Integer.parseInt(mS.split(" - ")[0]);

    String sql = "INSERT INTO docente_materias (docente_id, materia_id) VALUES (?, ?)";

    try (java.sql.PreparedStatement ps = this.conexion.prepareStatement(sql)) {
        ps.setInt(1, idDocente);
        ps.setInt(2, idMateria);
        
        if (ps.executeUpdate() > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Materia asignada con éxito");
            cargarTabla();
        }
    }
} catch (java.sql.SQLException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "La materia ya está asignada a este docente o hubo un error de BD: " + e.getMessage());
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error al procesar los códigos numéricos");
}



        // TODO add your handling code here:
    }//GEN-LAST:event_botonAsignarActionPerformed

    private void comboMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMateriasActionPerformed

    private void comboDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDocentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDocentesActionPerformed

    private void botonregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonregresarActionPerformed
                                             
    try {
        java.sql.Connection conActiva = Datos.getInstancia().getConexion();
        VentanaAdministrador va = new VentanaAdministrador(conActiva);
        va.setLocationRelativeTo(null);
        va.setVisible(true);
        this.dispose();
    } catch (Exception e) {
        System.out.println("Error al regresar al menu: " + e.getMessage());
    }

 // TODO add your handling code here:
    }//GEN-LAST:event_botonregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaMaterias(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAsignar;
    private javax.swing.JButton botonEliminarMateria;
    private javax.swing.JButton botonregresar;
    private javax.swing.JComboBox<String> comboDocentes;
    private javax.swing.JComboBox<String> comboMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAsignacion;
    // End of variables declaration//GEN-END:variables
 private void cargarComboDocentes() {
    comboDocentes.removeAllItems();
    String sql = "SELECT id, nombre FROM docentes";
    try (java.sql.PreparedStatement ps = this.conexion.prepareStatement(sql);
         java.sql.ResultSet rs = ps.executeQuery()) {
        while (rs.next()) {
            comboDocentes.addItem(rs.getInt("id") + " - " + rs.getString("nombre"));
        }
    } catch (java.sql.SQLException e) {
        System.out.println("Error al cargar docentes: " + e.getMessage());
    }
}


private void cargarComboMaterias() {
    comboMaterias.removeAllItems();
    String sql = "SELECT id, nombre FROM materias";
    try (java.sql.PreparedStatement ps = this.conexion.prepareStatement(sql);
         java.sql.ResultSet rs = ps.executeQuery()) {
        while (rs.next()) {
            comboMaterias.addItem(rs.getInt("id") + " - " + rs.getString("nombre"));
        }
    } catch (java.sql.SQLException e) {
        System.out.println("Error al cargar materias: " + e.getMessage());
    }
}


   

}

