/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaacademico;

public class VentanaDocente extends javax.swing.JFrame {
    
    private java.sql.Connection conexion;
    private int idDocente;

    public VentanaDocente(java.sql.Connection conexion, int idDocente) {
        initComponents();
        this.conexion = conexion;
        this.idDocente = idDocente;
        cargarMateriasDocente();
        
    }

    private void cargarMateriasDocente() {
        String[] columnas = {"Código", "Nombre de la Materia"};
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        String sql = "SELECT m.codigo, m.nombre FROM materias m " +
                     "INNER JOIN docente_materias dm ON m.id = dm.materia_id " +
                     "WHERE dm.docente_id = ? " +
                     "OR dm.docente_id = (SELECT id FROM docentes WHERE nombre = (SELECT nombre FROM usuarios WHERE idUsuario = ? LIMIT 1) LIMIT 1)";

        try (java.sql.PreparedStatement ps = this.conexion.prepareStatement(sql)) {
            ps.setInt(1, this.idDocente);
            ps.setInt(2, this.idDocente);
            
            try (java.sql.ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    String codigo = rs.getString("codigo");
                    String nombre = rs.getString("nombre");
                    Object[] fila = {codigo, nombre};
                    modelo.addRow(fila);
                }
            }
        } catch (java.sql.SQLException e) {
            System.out.println("Error al cargar materias: " + e.getMessage());
        }

        tablaMateriasDocente.setModel(modelo);
    }


    /**
     * Creates new form VentanaDocenteNueva
     */



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        botonEstudiantes = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonNiveles = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMateriasDocente = new javax.swing.JTable();
        labelUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        botonEstudiantes.setText("Estudiantes");
        jPanel2.add(botonEstudiantes);

        botonSalir.setText("Salir");
        botonSalir.addActionListener(this::botonSalirActionPerformed);
        jPanel2.add(botonSalir);

        botonNiveles.setText("Niveles");
        jPanel2.add(botonNiveles);

        tablaMateriasDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMateriasDocente);

        labelUsuario.setText("Hola, Docente!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsuario)
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
    try{
    com.mycompany.sistemaacademico.VentanaIngreso login = new com.mycompany.sistemaacademico.VentanaIngreso();
    login.setLocationRelativeTo(null);
    login.setVisible(true);
    this.dispose();
    }catch (Exception e){
        System.out.println("error al cerrar sesion: " + e.getMessage());
}       
    }//GEN-LAST:event_botonSalirActionPerformed


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEstudiantes;
    private javax.swing.JButton botonNiveles;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JTable tablaMateriasDocente;
    // End of variables declaration//GEN-END:variables




}
