/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaacademico;
import com.mycompany.sistemaacademico.*;



import javax.swing.table.DefaultTableModel;

/**
 *
 * @author esteb
 */
public class VentanaMaterias extends javax.swing.JFrame {

    public VentanaMaterias() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
 private void cargarTabla() {
    String[] columnas = {"Docente", "Materias Asignadas"};
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    String sql = "SELECT u.nombre AS docente, GROUP_CONCAT(m.nombre SEPARATOR ', ') AS materias " +
                 "FROM usuarios u " +
                 "LEFT JOIN docente_materias dm ON u.idUsuario = dm.docente_id " +
                 "LEFT JOIN materias m ON dm.materia_id = m.id " +
                 "WHERE u.rol = 'DOCENTE' " +
                 "GROUP BY u.idUsuario";

    try (java.sql.PreparedStatement ps = this.conexion.prepareStatement(sql);
         java.sql.ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            String docente = rs.getString("docente");
            String materias = rs.getString("materias");
            if (materias == null) {
                materias = "Ninguna";
            }
            Object[] fila = {docente, materias};
            modelo.addRow(fila);
        }

    } catch (java.sql.SQLException e) {
        System.out.println("Error al cargar tabla de materias: " + e.getMessage());
    }

    tablaAsignacion.setModel(modelo);
}


    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaMaterias.class.getName());

    /**
     * Creates new form VentanaMaterias
     */
  private java.sql.Connection conexion;


public VentanaMaterias(java.sql.Connection conexion) {
    initComponents();
    this.conexion = conexion;
    cargarTabla();
    cargarComboDocentes();
    cargarComboMaterias();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonAsignar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAsignacion = new javax.swing.JTable();
        botonEliminarMateria = new javax.swing.JButton();
        comboDocentes = new javax.swing.JComboBox<>();
        comboMaterias = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre Docente ");

        jLabel2.setText("Nombre Materia ");

        botonAsignar.setText("Asignar Materia");
        botonAsignar.addActionListener(this::botonAsignarActionPerformed);

        tablaAsignacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Docente", "Materias"
            }
        ));
        jScrollPane1.setViewportView(tablaAsignacion);

        botonEliminarMateria.setText("Eliminar Materia Seleccionada");
        botonEliminarMateria.addActionListener(this::botonEliminarMateriaActionPerformed);

        comboDocentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboMaterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonAsignar)
                                .addGap(52, 52, 52))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(botonEliminarMateria)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAsignar))
                .addGap(31, 31, 31)
                .addComponent(botonEliminarMateria)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void cargarComboDocentes() {
    comboDocentes.removeAllItems();
    String sql = "SELECT nombre FROM usuarios WHERE rol = 'DOCENTE'";
    try (java.sql.PreparedStatement ps = this.conexion.prepareStatement(sql);
         java.sql.ResultSet rs = ps.executeQuery()) {
        while (rs.next()) {
            comboDocentes.addItem(rs.getString("nombre"));
        }
    } catch (java.sql.SQLException e) {
        System.out.println("Error al cargar docentes: " + e.getMessage());
    }
}

private void cargarComboMaterias() {
    comboMaterias.removeAllItems();
    String sql = "SELECT nombre FROM materias";
    try (java.sql.PreparedStatement ps = this.conexion.prepareStatement(sql);
         java.sql.ResultSet rs = ps.executeQuery()) {
        while (rs.next()) {
            comboMaterias.addItem(rs.getString("nombre"));
        }
    } catch (java.sql.SQLException e) {
        System.out.println("Error al cargar materias: " + e.getMessage());
    }
}



    private void botonEliminarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarMateriaActionPerformed
int filaSeleccionada = tablaAsignacion.getSelectedRow();

if (filaSeleccionada == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione una fila de la tabla.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}

String nombreDocente = tablaAsignacion.getValueAt(filaSeleccionada, 0).toString();
String materiasTexto = tablaAsignacion.getValueAt(filaSeleccionada, 1).toString();

if (materiasTexto.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Este docente no tiene materias asignadas.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}

String[] opciones = materiasTexto.split(", ");
String materiaAEliminar = (String) javax.swing.JOptionPane.showInputDialog(
        this,
        "Seleccione la materia que desea eliminar:",
        "Modificar Materias",
        javax.swing.JOptionPane.QUESTION_MESSAGE,
        null,
        opciones,
        opciones[0]
);

if (materiaAEliminar != null) {
    Usuario docente = Datos.getInstancia().getUsuarioPorNombre(nombreDocente);
                if (docente != null) {
                com.mycompany.sistemaacademico.MateriaDAO mDAO = new com.mycompany.sistemaacademico.MateriaDAO(com.mycompany.sistemaacademico.Datos.getConexion());
                mDAO.eliminar(materiaAEliminar);
                cargarTabla();
                javax.swing.JOptionPane.showMessageDialog(this, "Materia eliminada con éxito.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

}
        
// TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarMateriaActionPerformed

    private void botonAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarActionPerformed
    try {
    String nombreDocente = (String) comboDocentes.getSelectedItem();
    String nombreMateria = (String) comboMaterias.getSelectedItem();

    if (nombreDocente == null || nombreMateria == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un docente y una materia.");
        return;
    }

    int idDocente = -1;
    int idMateria = -1;

    String sqlDocente = "SELECT idUsuario FROM usuarios WHERE nombre = ? AND rol = 'DOCENTE'";
    try (java.sql.PreparedStatement ps = this.conexion.prepareStatement(sqlDocente)) {
        ps.setString(1, nombreDocente);
        try (java.sql.ResultSet rs = ps.executeQuery()) {
            if (rs.next()) idDocente = rs.getInt("idUsuario");
        }
    }

    String sqlMateria = "SELECT id FROM materias WHERE nombre = ?";
    try (java.sql.PreparedStatement ps = this.conexion.prepareStatement(sqlMateria)) {
        ps.setString(1, nombreMateria);
        try (java.sql.ResultSet rs = ps.executeQuery()) {
            if (rs.next()) idMateria = rs.getInt("id");
        }
    }

    if (idDocente != -1 && idMateria != -1) {
        com.mycompany.sistemaacademico.MateriaDAO materiaDAO = new com.mycompany.sistemaacademico.MateriaDAO(this.conexion);
        if (materiaDAO.asignarMateriaADocente(idDocente, idMateria)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Materia asignada con éxito.");
            cargarTabla();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "El docente ya tiene asignada esta materia.");
        }
    }
} catch (Exception e) {
    System.out.println("Error al asignar: " + e.getMessage());
}



        // TODO add your handling code here:
    }//GEN-LAST:event_botonAsignarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaMaterias(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAsignar;
    private javax.swing.JButton botonEliminarMateria;
    private javax.swing.JComboBox<String> comboDocentes;
    private javax.swing.JComboBox<String> comboMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAsignacion;
    // End of variables declaration//GEN-END:variables
}
