/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaacademico;

import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author -PC
 */
public class VentanaCrearUsuario extends javax.swing.JFrame {

    private Usuario usuario;

    /**
     * Creates new form VentanaCrearUsuario
     */
    public VentanaCrearUsuario() {
        initComponents();
        DefaultComboBoxModel model = new DefaultComboBoxModel(Rol.values());
        cbxRolUsuario.setModel(model);
    }

    public VentanaCrearUsuario(int id) {
        initComponents();
        DefaultComboBoxModel model = new DefaultComboBoxModel(Rol.values());
        cbxRolUsuario.setModel(model);

        var conexion = Datos.getInstancia().getConexion();
        var dao = new UsuarioDAO(conexion);
        usuario = dao.buscarPorID(id);

        if (usuario == null) {
            JOptionPane.showMessageDialog(null,
                    "No se encuentra el usuario con ID: " + id,
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        txtNombreUsuario.setText(usuario.getNombre());
        txtPasswordUsuario.setText(usuario.getPassword());
        cbxRolUsuario.setSelectedItem(usuario.getRol());

        labelTitulo.setText("Edite el usuario");
        botonCrear.setText("Editar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPasswordUsuario = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbxRolUsuario = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtImagenURL = new javax.swing.JTextField();
        botonCargar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        botonCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(6, 1, 0, 20));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Ingrese el nuevo usuario");
        jPanel1.add(labelTitulo);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLabel2.setText("Nombre de Usuario:");
        jPanel2.add(jLabel2);
        jPanel2.add(txtNombreUsuario);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLabel3.setText("Contraseña:");
        jPanel3.add(jLabel3);
        jPanel3.add(txtPasswordUsuario);

        jPanel1.add(jPanel3);

        jPanel5.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLabel4.setText("Rol:");
        jPanel5.add(jLabel4);
        jPanel5.add(cbxRolUsuario);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLabel5.setText("Imagen de Perfil:");
        jPanel6.add(jLabel5);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        txtImagenURL.setEditable(false);
        jPanel7.add(txtImagenURL);

        botonCargar.setText("Cargar");
        botonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarActionPerformed(evt);
            }
        });
        jPanel7.add(botonCargar);

        jPanel6.add(jPanel7);

        jPanel1.add(jPanel6);

        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });
        jPanel4.add(botonCrear);

        jPanel1.add(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // TODO add your handling code here:
     try {
        String nombre = txtNombreUsuario.getText();
        String password = String.valueOf(txtPasswordUsuario.getPassword());
        String rolSeleccionado = cbxRolUsuario.getSelectedItem().toString();
        String imagenURL = txtImagenURL.getText();

        if (nombre.isEmpty() || password.isEmpty() || rolSeleccionado.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor llene todos los campos obligatorios");
            return;
        }

        Usuario nuevoUsuario = new Usuario();
        nuevoUsuario.setNombre(nombre);
        nuevoUsuario.setPassword(password);
        nuevoUsuario.setRol(Rol.valueOf(rolSeleccionado.toUpperCase()));
        nuevoUsuario.setImagenURL(imagenURL);

        java.sql.Connection con = Datos.getConexion();
        UsuarioDAO usuarioDAO = new UsuarioDAO(con);

        if (usuarioDAO.insertar(nuevoUsuario)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario creado con éxito");
            txtNombreUsuario.setText("");
            txtPasswordUsuario.setText("");
            txtImagenURL.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar el usuario");
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error en los datos ingresados o variables mal nombradas");
    
}

    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();

        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter(
                "Archivos de Imagen", "jpg", "jpeg", "png", "gif",
                "bmp");
        fileChooser.setFileFilter(imageFilter);

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Archivo seleccionado: " + selectedFile.getName());
            txtImagenURL.setText(selectedFile.getAbsolutePath());
        } else {
            System.out.println("No se seleccionó ningún archivo."); 
        } 
    }//GEN-LAST:event_botonCargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCrearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargar;
    private javax.swing.JButton botonCrear;
    private javax.swing.JComboBox<String> cbxRolUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField txtImagenURL;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JPasswordField txtPasswordUsuario;
    // End of variables declaration//GEN-END:variables
}
