/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaacademico;


/**
 *
 * @author esteb
 */
public class VentanaVerDocentes extends javax.swing.JFrame {
    
    

    /**
     * Creates new form VentanaVerDocentes
     */
        private java.sql.Connection conexion;

    public VentanaVerDocentes(java.sql.Connection conexion) {
        initComponents();
        this.conexion = conexion;
        cargarTablaDocentes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDocentes = new javax.swing.JTable();
        botonRegresarAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Docentes");

        tablaDocentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "materias"
            }
        ));
        jScrollPane1.setViewportView(tablaDocentes);

        botonRegresarAdmin.setText("Regresar");
        botonRegresarAdmin.addActionListener(this::botonRegresarAdminActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonRegresarAdmin)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRegresarAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarAdminActionPerformed
                                                         
    try {
        java.sql.Connection conActiva = com.mycompany.sistemaacademico.Datos.getInstancia().getConexion();
        com.mycompany.sistemaacademico.VentanaAdministrador va = new com.mycompany.sistemaacademico.VentanaAdministrador(conActiva);
        va.setLocationRelativeTo(null);
        va.setVisible(true);
        this.dispose();
    } catch (Exception e) {
        System.out.println("Error al regresar al menú principal: " + e.getMessage());
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarAdminActionPerformed

    /**
     * @param args the command line arguments
     */
  private void cargarTablaDocentes() {
    String[] columnas = {"ID", "Nombre", "Correo Electrónico"};
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    String sql = "SELECT id, nombre, correo FROM docentes";
    java.sql.Connection con = com.mycompany.sistemaacademico.Datos.getInstancia().getConexion();

    try (java.sql.PreparedStatement ps = con.prepareStatement(sql);
         java.sql.ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            Object[] fila = {
                rs.getInt("id"),
                rs.getString("nombre"),
                rs.getString("correo")
            };
            modelo.addRow(fila);
        }

    } catch (java.sql.SQLException e) {
        System.out.println("Error al cargar la tabla de docentes: " + e.getMessage());
    }

    tablaDocentes.setModel(modelo);
}

          private void botonMateriasActionPerformed(java.awt.event.ActionEvent evt) {                                              
        com.mycompany.sistemaacademico.VentanaMaterias vm = new com.mycompany.sistemaacademico.VentanaMaterias(this.conexion);
        vm.setLocationRelativeTo(this);
        vm.setVisible(true);
    } 
                                          

       private void botonDocentesActionPerformed(java.awt.event.ActionEvent evt) {                                              
        com.mycompany.sistemaacademico.VentanaVerDocentes vvd = new com.mycompany.sistemaacademico.VentanaVerDocentes(this.conexion);
        vvd.setLocationRelativeTo(this);
        vvd.setVisible(true);
    } 
                                           



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresarAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDocentes;
    // End of variables declaration//GEN-END:variables

   
   
}
